"""
APIx — SQLAlchemy Models (Normalized Fare-Data Schema)
==========================================================

Source of truth for the Postgres schema — Alembic's migrations
(app/db/migrations/) are autogenerated from `Base.metadata` here, so a
schema change means editing a model class and running
`alembic revision --autogenerate`, not hand-writing SQL.

Three tables, matching the normalization raw_fare_item.py's own docstring
anticipates ("a future Postgres loader maps this shape onto whatever
normalized schema the database uses, resolving carrier/route dimension
tables at load time rather than scrape time"):

  * Carrier            -- dimension: one row per airline (carrier_code).
  * Route               -- dimension: one row per (origin, destination)
                            directed city pair (route_id).
  * FareObservation      -- fact: one row per scraped fare quote. Deliberately
                            APPEND-ONLY / time-series — a route's fare at
                            T+7 today and T+7 tomorrow are two distinct rows,
                            never an update-in-place, because the whole point
                            of this table is charting how a fare moves across
                            successive scrape runs.

carrier_code and route_id are used directly as primary keys (not surrogate
integers) because both are already stable, short, externally-defined
identifiers that every raw_fare_item carries (see raw_fare_item.py) — a
surrogate id would just add a join for zero benefit.
"""

from __future__ import annotations

import datetime
from decimal import Decimal

from sqlalchemy import (
    CheckConstraint,
    ForeignKey,
    Index,
    Numeric,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Carrier(Base):
    """One row per airline — dimension table for FareObservation.carrier_code."""

    __tablename__ = "carriers"

    carrier_code: Mapped[str] = mapped_column(primary_key=True)  # e.g. "QP"
    airline_name: Mapped[str] = mapped_column(nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(server_default=func.now())

    observations: Mapped[list["FareObservation"]] = relationship(back_populates="carrier")

    def __repr__(self) -> str:  # pragma: no cover - debugging aid only
        return f"Carrier(carrier_code={self.carrier_code!r}, airline_name={self.airline_name!r})"


class Route(Base):
    """One row per directed (origin, destination) city pair — dimension
    table for FareObservation.route_id."""

    __tablename__ = "routes"
    __table_args__ = (
        CheckConstraint("origin <> destination", name="ck_routes_origin_ne_destination"),
    )

    route_id: Mapped[str] = mapped_column(primary_key=True)  # e.g. "DEL-BOM"
    origin: Mapped[str] = mapped_column(nullable=False)
    destination: Mapped[str] = mapped_column(nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(server_default=func.now())

    observations: Mapped[list["FareObservation"]] = relationship(back_populates="route")

    def __repr__(self) -> str:  # pragma: no cover - debugging aid only
        return f"Route(route_id={self.route_id!r})"


class FareObservation(Base):
    """One row per scraped fare quote — the append-only fact table the
    dashboard's time-series charts are built from.

    Uniqueness is deliberately keyed on (route_id, carrier_code,
    flight_number, departure_time, lead_window, scraped_at) rather than
    dropping scraped_at from the key: this is a time series, so two
    observations of the same flight/window taken at different times are
    both real data points, not duplicates to collapse. In practice this
    constraint's main effect is guarding against double-loading the exact
    same already-serialized batch (e.g. an accidental rerun of the loader
    against one JSON file) — build_raw_fare_item() timestamps each item
    individually (see raw_fare_item.py), so two genuinely separate scrape
    runs will essentially never collide on scraped_at and will correctly
    both land as distinct rows.
    """

    __tablename__ = "fare_observations"
    __table_args__ = (
        UniqueConstraint(
            "route_id", "carrier_code", "flight_number", "departure_time",
            "lead_window", "scraped_at",
            name="uq_fare_observations_identity",
        ),
        Index(
            "ix_fare_observations_route_scraped_at",
            "route_id", "lead_window", "scraped_at",
        ),
        Index(
            "ix_fare_observations_route_id_scraped_at",
            "route_id", "scraped_at",
        ),
        Index("ix_fare_observations_lead_window", "lead_window"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    route_id: Mapped[str] = mapped_column(ForeignKey("routes.route_id"), nullable=False)
    carrier_code: Mapped[str] = mapped_column(ForeignKey("carriers.carrier_code"), nullable=False, index=True)

    flight_number: Mapped[str | None] = mapped_column(nullable=True)
    departure_time: Mapped[datetime.datetime | None] = mapped_column(nullable=True)  # naive — source gives no offset
    arrival_time: Mapped[datetime.datetime | None] = mapped_column(nullable=True)

    base_fare: Mapped[Decimal | None] = mapped_column(Numeric(10, 2), nullable=True)
    taxes_and_fees: Mapped[Decimal | None] = mapped_column(Numeric(10, 2), nullable=True)
    total_fare: Mapped[Decimal | None] = mapped_column(Numeric(10, 2), nullable=True)
    seats_left: Mapped[int | None] = mapped_column(nullable=True)
    fare_class: Mapped[str | None] = mapped_column(nullable=True)  # source's own fare-bucket code, e.g. "EC"

    lead_window: Mapped[str] = mapped_column(nullable=False)  # e.g. "T+7"
    source_name: Mapped[str] = mapped_column(nullable=False)  # e.g. "akasa_air"
    source_type: Mapped[str] = mapped_column(nullable=False)  # e.g. "airline_direct"

    scraped_at: Mapped[datetime.datetime] = mapped_column(nullable=False)  # UTC, from scraped_at_timestamp
    loaded_at: Mapped[datetime.datetime] = mapped_column(server_default=func.now())

    route: Mapped[Route] = relationship(back_populates="observations")
    carrier: Mapped[Carrier] = relationship(back_populates="observations")

    def __repr__(self) -> str:  # pragma: no cover - debugging aid only
        return (
            f"FareObservation(route_id={self.route_id!r}, lead_window={self.lead_window!r}, "
            f"total_fare={self.total_fare!r}, scraped_at={self.scraped_at!r})"
        )


class ScrapeRun(Base):
    """One row per invocation of run_daily_scrape.py — the audit trail that
    turns "the daily job is supposed to run unattended" into something
    observable: a dashboard health panel, or a human checking on the
    scheduler after a week away, reads this table rather than grepping
    rotating log files on the machine the scheduler happens to run on.

    Written in two steps by run_daily_scrape.main(): one row is inserted
    (status=RUNNING) before the batch starts, then updated in place once it
    finishes (or crashes) — so a run that never reaches its second write
    (e.g. the process is killed) is itself visible as a row permanently
    stuck at RUNNING, rather than silently missing.
    """

    __tablename__ = "scrape_runs"
    __table_args__ = (
        Index("ix_scrape_runs_started_at", "started_at"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    started_at: Mapped[datetime.datetime] = mapped_column(nullable=False)
    finished_at: Mapped[datetime.datetime | None] = mapped_column(nullable=True)
    status: Mapped[str] = mapped_column(nullable=False, default="running")  # running|success|partial|failed

    tasks_total: Mapped[int] = mapped_column(nullable=False, default=0)
    items_collected: Mapped[int] = mapped_column(nullable=False, default=0)
    items_loaded: Mapped[int] = mapped_column(nullable=False, default=0)
    missing_data_summary: Mapped[str | None] = mapped_column(nullable=True)  # JSON-encoded {reason: count}
    error_message: Mapped[str | None] = mapped_column(nullable=True)

    created_at: Mapped[datetime.datetime] = mapped_column(server_default=func.now())

    def __repr__(self) -> str:  # pragma: no cover - debugging aid only
        return (
            f"ScrapeRun(id={self.id!r}, status={self.status!r}, "
            f"started_at={self.started_at!r}, items_loaded={self.items_loaded!r})"
        )


class FareIndexDaily(Base):
    """One row per (index_date, lead_window) — the daily Airfare Price
    Index value computed by app/index/psd_index.py, persisted here so the
    dashboard/API reads a precomputed series instead of re-running the
    weighted-index calculation on every request.

    lead_window holds either a real AP-window label ("T+7") or the sentinel
    app.index.psd_index.OVERALL_LABEL for the one blended row per date
    (equal-weighted across whichever AP windows have data that day) —
    deliberately a string sentinel and NOT SQL NULL: Postgres's UNIQUE
    constraint (and therefore ON CONFLICT) never treats two NULLs as equal,
    so a nullable lead_window would let every recompute silently INSERT a
    fresh "overall" row instead of updating the existing one, defeating
    the whole point of upserting on (index_date, lead_window) — caught by
    tests/test_psd_index.py's idempotency test before it ever shipped.
    """

    __tablename__ = "fare_index_daily"
    __table_args__ = (
        UniqueConstraint("index_date", "lead_window", name="uq_fare_index_daily_date_window"),
        Index("ix_fare_index_daily_index_date", "index_date"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    index_date: Mapped[datetime.date] = mapped_column(nullable=False)
    lead_window: Mapped[str] = mapped_column(nullable=False)  # AP window label, or OVERALL_LABEL
    index_value: Mapped[Decimal] = mapped_column(Numeric(10, 4), nullable=False)
    base_date: Mapped[datetime.date] = mapped_column(nullable=False)
    route_count: Mapped[int] = mapped_column(nullable=False)  # routes actually contributing this row

    computed_at: Mapped[datetime.datetime] = mapped_column(server_default=func.now(), onupdate=func.now())

    def __repr__(self) -> str:  # pragma: no cover - debugging aid only
        return (
            f"FareIndexDaily(index_date={self.index_date!r}, lead_window={self.lead_window!r}, "
            f"index_value={self.index_value!r})"
        )
