"""add fare_class to fare_observations

Revision ID: 101c0140a218
Revises: 9ed334a2a703
Create Date: 2026-08-31 20:56:55.081550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '101c0140a218'
down_revision: Union[str, Sequence[str], None] = '9ed334a2a703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fare_observations', sa.Column('fare_class', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fare_observations', 'fare_class')
    # ### end Alembic commands ###
