"""add scrape_runs and fare_index_daily tables

Revision ID: 22c258ba5de0
Revises: 101c0140a218
Create Date: 2026-09-01 22:11:23.610797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c258ba5de0'
down_revision: Union[str, Sequence[str], None] = '101c0140a218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fare_index_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_date', sa.Date(), nullable=False),
    sa.Column('lead_window', sa.String(), nullable=True),
    sa.Column('index_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('base_date', sa.Date(), nullable=False),
    sa.Column('route_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_date', 'lead_window', name='uq_fare_index_daily_date_window')
    )
    op.create_index('ix_fare_index_daily_index_date', 'fare_index_daily', ['index_date'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tasks_total', sa.Integer(), nullable=False),
    sa.Column('items_collected', sa.Integer(), nullable=False),
    sa.Column('items_loaded', sa.Integer(), nullable=False),
    sa.Column('missing_data_summary', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scrape_runs_started_at', 'scrape_runs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scrape_runs_started_at', table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_index('ix_fare_index_daily_index_date', table_name='fare_index_daily')
    op.drop_table('fare_index_daily')
    # ### end Alembic commands ###
