"""make fare_index_daily.lead_window not null

Revision ID: 6c88c6e41e45
Revises: 22c258ba5de0
Create Date: 2026-09-01 22:15:49.004436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c88c6e41e45'
down_revision: Union[str, Sequence[str], None] = '22c258ba5de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fare_index_daily', 'lead_window',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fare_index_daily', 'lead_window',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
