"""initial schema: carriers, routes, fare_observations

Revision ID: 9ed334a2a703
Revises: 
Create Date: 2026-08-31 20:33:42.183650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed334a2a703'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('carrier_code', sa.String(), nullable=False),
    sa.Column('airline_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('carrier_code')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('origin <> destination', name='ck_routes_origin_ne_destination'),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('fare_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('carrier_code', sa.String(), nullable=False),
    sa.Column('flight_number', sa.String(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('taxes_and_fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_fare', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('seats_left', sa.Integer(), nullable=True),
    sa.Column('lead_window', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_code'], ['carriers.carrier_code'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'carrier_code', 'flight_number', 'departure_time', 'lead_window', 'scraped_at', name='uq_fare_observations_identity')
    )
    op.create_index(op.f('ix_fare_observations_carrier_code'), 'fare_observations', ['carrier_code'], unique=False)
    op.create_index('ix_fare_observations_lead_window', 'fare_observations', ['lead_window'], unique=False)
    op.create_index('ix_fare_observations_route_id_scraped_at', 'fare_observations', ['route_id', 'scraped_at'], unique=False)
    op.create_index('ix_fare_observations_route_scraped_at', 'fare_observations', ['route_id', 'lead_window', 'scraped_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fare_observations_route_scraped_at', table_name='fare_observations')
    op.drop_index('ix_fare_observations_route_id_scraped_at', table_name='fare_observations')
    op.drop_index('ix_fare_observations_lead_window', table_name='fare_observations')
    op.drop_index(op.f('ix_fare_observations_carrier_code'), table_name='fare_observations')
    op.drop_table('fare_observations')
    op.drop_table('routes')
    op.drop_table('carriers')
    # ### end Alembic commands ###
